# Generated by Django 3.2 on 2021-04-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cena_b2b',
            new_name='price_b2b',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cena_b2c',
            new_name='price_b2c',
        ),
    ]
